### Upload Document

POST http://127.0.0.1:8000/api/documents
Authorization: Bearer 11|C5pccAkYz1V2RmlfIkzozdZV5Z4clzibBTi4ULm552014475
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

My second Document
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="sample3.txt"
Content-Type: text/plain

< ./sample2.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--
