### Upload Document

POST http://127.0.0.1:8000/api/documents
Authorization: Bearer 9|cDiUhXbykHynZZEUWBrEiUn7FnHjoCmNRCdYPx4Pba2ad056
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

My First Document
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="sample.txt"
Content-Type: text/plain

< ./sample.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--
